args_source_map = {
    "${does offer}": ["does offer", "does run", "does hold", "does have", "does launch", "offers", "runs", "holds", "features", "has", "launches"],
    "${New Year sale}": ["New Year sale", "New Year sale event"],
    "${to celebrate the new year}": ["to kick off the new year", "to embrace ${the new year}", "to welcome ${the new year}", "to celebrate ${the new year}", "in celebration of the new year"],
    "${the new year}": ["the new year", "the start of the year", "the beginning of the year", "the arrival of the new year", "the arrival of the year ahead", "the start of the new year", "the beginning of the new year"],
    "${This}": ["this", "the"],
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${begins}": ["begins", "starts", "kicks off", "rolls out"],
    "${in the last week of December}": ["in the last week of December", "in the last days of December", "in the final week of December", "in the final days of December", "around the end of December", "in the end of December", "around the December's end", "around late December", "as December ends", "in late December", "from late December", "by the end of December"],
    "${continues through}": ["continues through", "extends through", "runs through", "lasts through", "goes on through", "carries on through", "keeps going through", "continues throughout", "extends throughout", "runs throughout", "lasts throughout", "goes on throughout", "carries on throughout", "keeps going throughout", "remains active through", "remains active throughout", "remains available through", "remains available throughout", "stays live through", "stays live throughout", "remains live through", "remains live throughout"],
    "${the first week of January}": ["the first week of January", "the first days of January", "the first few days of January", "January's first few days", "the initial week of January", "the initial days of January", "the new year's first week", "the early days of January"],
    "${making it}": ["creating", "making it", "presenting", "offering", "providing"],
    "${a great}": ["an excellent", "a prime", "a favorable", "the best", "an ideal", "a great", "a fantastic", "a wonderful", "an amazing", "a superb", "a terrific", "a perfect", "a golden", "a top-notch", "a remarkable", "a favorable", "an exceptional"],
    "${opportunity}": ["opportunity", "chance", "occasion", "moment", "time"],
    "${find}": ["find", "get", "enjoy", "receive", "claim", "access", "grab", "snag", "hunt for", "catch", "discover"],
    "${bargains}": ["bargains", "deals", "discounts", "savings"],
    "${a wide range of}": ["many", "a lot of", "a variety of", "plenty of", "a wide range of", "numerous", "a large number of", "a great number of", "various", "many kinds of"],
    "${products}": ["products", "items", "merchandise"],
    "${Christmas}": ["Christmas", "Christmas day", "the 25th December", "December 25th"],
    "${leading up to}": ["leading up to", "ahead of", "before", "right before", "prior to", "just before"],
    "${catch}": ["catch", "get", "enjoy", "receive", "grab", "unlock", "claim", "access", "embrace", "seize", "benefit from", "score"],
    "${subscribe to}": ["subscribe to", "enrol in", "register for", "sign up for"],
    "${newsletter}": ["newsletter", "email newsletter", "mailing list", "email list", "email alerts"],
    "${announcements}": ["announcements", "updates", "news", "messages", "releases", "notifications"],
    # "${announcements2}": ["与${announcements1}取值范围相同，但与${announcements1}不能取同一值"],
    "${or}": ["and", "or"],
    "${promotions}": ["promotions", "discounts", "sales", "event", "sale event", "shopping event", "saving event"],
    "${get}": ["get", "enjoy", "profit from", "benefit from", "receive", "claim", "obtain", "grab", "unlock", "access", "embrace", "take advantage of"],
    "${ranging from 20% to 60%}": ["ranging from ${20%} to ${60%}", "spanning ${20%} to ${60%}", "spanning from ${20%} to ${60%}", "from ${20%} to ${60%}", "extending from ${20%} to ${60%}", "from ${20%} up to ${60%}", "varying between ${20%} to ${60%}"],
    "${20%}": ["20%", "30%"],
    "${60%}": ["50%", "60%", "70%", "50% or more", "60% or more", "70% or more"],
    "${during}": ["during", "at the time of", "over the period of", "with"],
    "${can}": ["can", "may", "might", "could"],
    "${vary}": ["vary", "differ", "change", "be different"],
    "${based on}": ["based on", "based upon", "depending on", "by", "with", "according to"],
    "${sale promotions}": ["sale promotions", "deals", "promotions", "offers", "discounts", "sales", "sale event"],
    "${beginning}": ["beginning", "starting"],
    "${continuing through}": ["continuing through", "extending through", "running through", "lasting through", "going on through", "carrying on through", "keeping going through", "continuing throughout", "extending throughout", "running throughout", "lasting throughout", "going on throughout", "carrying on throughout", "keeping going throughout", "remaining active through", "remaining active throughout", "remaining available through", "remaining available throughout", "staying live through", "staying live throughout", "remaining live through", "remaining live throughout"],
    "${specific sale dates}": ["specific sale dates", "sale dates", "event dates", "New Year sale dates", "exact sale dates", "particular sale dates"],
    "${promotion details}": ["promotion details", "offer details", "deal information", "savings information", "discount details"],
}
