args_source_map = {
    "${sales and promotions}": ["deals and promotions", "promotions and deals", "promotions", "deals", "deals and discounts", "sales and promotions", "promos and discounts", "promos and deals", "promos and sales", "discounts and deals", "discounts and sales", "discounts and promotions", "promotions and discounts", "promotions and sales", "sales and discounts", "sales"],
    "${during}": ["during", "throughout"],
    "${sales}": ["sales", "deals", "sale events", "savings events", "clearance", "holiday sales", "seasonal events", "seasonal deals", "seasonal sales", "event sales", "flash sales", "flash deals", "seasonal sale events"],
    "${feature}": ["feature", "include", "highlight", "come with"],
    "${discounts}": ["discounts", "savings", "reduced prices", "markdowns", "price cuts", "lower prices"],
    "${popular}": ["popular", "trending", "best-selling", "top-rated", "most-loved", "must-have"],
    "${items}": ["products", "items", "merchandise"],
    "${website}": ["website", "official website", "site", "official site"],
    "${subscribe to}": ["subscribe to", "enroll in", "register for", "sign up for"],
    "${newsletter}": ["newsletter", "email newsletter", "mailing list", "email list", "email alerts", "email newsletters"],
    "${stay informed about}": ["stay informed about", "keep track of", "be informed about", "get the scoop on", "keep updated on", "stay updated on", "keep informed of", "stay current with", "follow"],
    "${sales events}": ["events", "sales", "promotions", "sales events", "sale events", "savings events", "saving events", "shopping events"],
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${start}": ["start", "begin", "kick off", "roll out"],
    "${a few days}": ["several days", "a couple of days", "a few days", "a short period"],
    "${before}": ["ahead of", "before", "right before", "prior to", "just before", "leading to"],
    "${continue through}": ["continue through", "extend through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "extend throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout", "remain live through", "remain live throughout", "extend into", "continue until", "extend until", "last until", "carry on until", "span through", "remain active until", "remain available until", "stay live until", "remain live until"],
    "${entire}": ["entire", "whole"],
    "${allows shoppers to}": ["${allows} ${shoppers} to", "lets ${shoppers}", "${gives} ${shoppers} the ${opportunity} to", "helps ${shoppers}", "ensures ${shoppers} can", "means ${shoppers} can"],
    "${allows}": ["allows", "enables", "invites"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${gives}": ["gives", "offers", "provides"],
    "${opportunity}": ["opportunity", "chance", "option"],
    "${deals}": ["deals", "promotions", "discounts", "sales"],
    "${the holiday}": ["the holiday", "Memorial Day", "May 26th", "May 26, 2025", "Mon, May 26"],
    "${last for}": ["continue for", "go on for", "keep going for", "last for", "run for"],
    "${beginning}": ["beginning", "starting"],
    "${continuing through}": ["continuing through", "extending through", "running through", "lasting through", "going on through", "carrying on through", "keeping going through", "continuing throughout", "extending throughout", "running throughout", "lasting throughout", "going on throughout", "carrying on throughout", "keeping going throughout", "remaining active through", "remaining active throughout", "remaining available through", "remaining available throughout", "staying live through", "staying live throughout", "remaining live through", "remaining live throughout"],
    "${Be sure to check}": ["${Be sure} to ${check}", "Stay tuned to", "Keep an eye on", "Check back on", "Take a moment to", "Stay updated by checking", "Keep checking back on", "Visit"],
    "${Be sure}": ["be sure", "make sure", "remember", "don't forget"],
    "${check}": ["check", "check out", "browse", "follow"],
    "${social media}": ["social media", "social media channels"],
    "${regularly}": ["regularly", "often", "frequently"],
    "${catch}": ["catch", "find", "grab", "unlock"],
    "${limited-time offers}": ["limited-time offers", "limited-time deals", "limited-time sales", "limited-time promotions", "flash offers", "flash deals", "flash sales", "flash promotions"],
    "${special discounts}": ["special discounts", "exclusive discounts", "extra discounts", "special savings", "exclusive savings", "extra savings"],
    "${find}": ["find", "get", "enjoy", "receive", "claim", "access", "grab", "snag", "catch", "discover", "claim", "unlock", "secure", "seize"],
    "${ranging from 10% to 50%}": ["ranging from ${10%} to ${50%}", "spanning ${10%} to ${50%}", "spanning from ${10%} to ${50%}", "from ${10%} to ${50%}", "extending from ${10%} to ${50%}", "from ${10%} up to ${50%}", "varying between ${10%} to ${50%}"],
    "${10%}": ["10%", "20%", "30%"],
    "${50%}": ["50%", "60%", "70%", "50% or more", "60% or more", "70% or more"],
    "${various}": ["various", "all kinds of", "a variety of", "all sorts of", "a range of", "a wide range of", "an array of", "plenty of", "a diverse range of"],
    "${products}": ["products", "items", "merchandise", "supplies"],
    "${stay updated on the latest}": ["stay updated on the newest", "keep informed of the newest", "stay current with the newest", "get the newest", "keep up with the newest", "catch the newest", "receive updates on the newest", "stay updated on the latest", "keep informed of the latest", "stay current with the latest", "get the latest", "keep up with the latest", "catch the latest", "receive updates on the latest", "stay updated on the most current", "keep informed of the most current", "get the most current", "keep up with the most current", "catch the most current", "receive updates on the most current", "keep informed of the up-to-date", "stay current with the up-to-date"],
    "${deals and promotions}": ["deals and promotions", "promotions and deals", "promotions", "deals", "deals and discounts", "sales and promotions", "promos and discounts", "promos and deals", "promos and sales", "discounts and deals", "discounts and sales", "discounts and promotions", "promotions and discounts", "promotions and sales", "sales and discounts", "sales"],
    "${Keep an eye on}": ["Look out for", "Look for", "Pay attention to", "Check for", "Stay tuned for", "Look around for", "Keep an eye on", "Check out", "Check"],
    "${take advantage of}": ["take advantage of", "make the most of", "score", "get", "enjoy", "grab", "snag", "claim", "unlock", "secure", "find", "access", "receive", "discover"],
}
