args_source_map = {
    # "${Remember to}": ["Remember to", "Don't forget to", "Be sure to", "Make sure to", "It's essential to", "Always remember to", "Don't miss to", "Try to", "Ensure to", "Don't hesitate to"],
    # "${apply}": ["apply", "redeem", "use", "enter", "add", "submit "],
    # "${code}": ["code", "promo code", "coupon code", "discount code", "offer code", "coupon", "special code"],
    # "${Additionally}": ["additionally", "in addtion", "moreover", "what's more", "beyond that", "besides", "plus"],
    # "${eligible}": ["eligible", "qualified", "verified"],
    # "${military members}": ["military members", "military personnel", "service members", "military staff", "service men & women", "military service members"],
    # "${enjoy}": ["enjoy", "get", "receive", "take", "grab", "unlock", "claim", "access", "embrace", "take advantage of"],
    "${Currently}": ["currently", "at this time", "as of now", "in this moment", "at present", "at the moment", "right now", "at this moment"],
    "${does not offer}": ["does not offer", "does not provide", "does not give", "does not have", "doesn't offer", "doesn't provide", "doesn't give", "doesn't have"],
    "${year-round}": ["year-round", "all-year", "yearlong", "full-year", "ongoing", "long-term", "regular", "specific", "dedicated", "specialized"],
    "${special}": ["special", "exclusive", "unique", "limited-time", "seasonal"],
    "${However,}": ["however,", "nevertheless,", "even so,", "still,", "despite that,", "even though,", "but", "while"],
    "${save up to discount}": ["save up to ${BEST_DISCOUNT}", "enjoy up to ${BEST_DISCOUNT} off", "get up to ${BEST_DISCOUNT} off", "receive up to ${BEST_DISCOUNT} off", "take up to ${BEST_DISCOUNT} off", "grab up to ${BEST_DISCOUNT} off", "unlock up to ${BEST_DISCOUNT} off", "claim up to ${BEST_DISCOUNT} off", "embrace up to ${BEST_DISCOUNT} off", "obtain up to ${BEST_DISCOUNT} off", "secure up to ${BEST_DISCOUNT} off", "snag up to ${BEST_DISCOUNT} off", "score up to ${BEST_DISCOUNT} off", "enjoy ${a} ${BEST_DISCOUNT} discount", "get ${a} ${BEST_DISCOUNT} discount", "receive ${a} ${BEST_DISCOUNT} discount", "take ${a} ${BEST_DISCOUNT} discount", "grab ${a} ${BEST_DISCOUNT} discount", "unlock ${a} ${BEST_DISCOUNT} discount", "claim ${a} ${BEST_DISCOUNT} discount", "embrace ${a} ${BEST_DISCOUNT} discount", "obtain ${a} ${BEST_DISCOUNT} discount", "secure ${a} ${BEST_DISCOUNT} discount", "snag ${a} ${BEST_DISCOUNT} discount", "score ${a} ${BEST_DISCOUNT} discount"],
    "${latest}": ["latest", "newest", "most recent", "current", "up-to-date", "most updated", "daily updated", "newly released", "newly issued"],
    "${coupons and discounts}": ["coupons and discounts", "coupons and promo codes", "coupons and deals", "coupons and sales", "coupons and promotions", "coupons and offers", "offers", "discounts and coupons", "discounts and promo codes", "discounts and deals", "discounts and sales", "discounts and promotions", "discounts and offers", "promo codes and coupons", "promo codes and discounts", "promo codes and deals", "promo codes and sales", "promo codes and offers", "promotions and coupons", "promotions and discounts", "promotions and deals", "promotions and sales", "promotions and offers", "deals and coupons", "deals and discounts", "deals and promo codes", "deals and promotions", "sales and offers", "sales and coupons", "sales and discounts", "sales and promo codes", "sales and promotions", "offers and discounts", "offers and promo codes", "offers and promotions", "offers and savings", "promos and coupons", "promos and discounts", "promos and deals", "promos and sales", "promos and offers", "discounts and savings", "promotions and savings", "promos and savings"],
    "${still}": ["still", "also", "always"],
    "${exclusively for}": ["exclusively for", "tailored for", "designed for", "for", "customized for", "intended for", "made for", "suitable for", "targeted at"],
    "${throughout the year}": ["throughout the year", "all year round", "across the year", "spanning the year", "all year long", "for the whole year", "during the entire year", "for the full year", "for the entire year"],
    "${coupons, promotions and special savings events}": ["coupons and promotions", "coupons and special savings events", "promotions and special savings events", "promotions and coupons", "coupons and discounts", "coupons and promo codes", "coupons and deals", "coupons and sales", "discounts and coupons", "discounts and promo codes", "discounts and deals", "discounts and sales", "discounts and promotions", "promo codes and coupons", "promo codes and discounts", "promo codes and deals", "promo codes and sales", "promotions and discounts", "promotions and deals", "promotions and sales", "deals and coupons", "deals and discounts", "deals and promo codes", "deals and promotions", "sales and coupons", "sales and discounts", "sales and promo codes", "sales and promotions", "promos and coupons", "promos and discounts", "promos and deals", "promos and sales", "discounts and savings events", "promotions and savings events", "promo codes and savings events", "promos and savings events"],
    "${take advantage of}": ["take advantage of", "make use of", "enjoy", "seize", "grab", "benefit from", "use", "make the most of", "get", "claim", "embrace"],
    "${general promotions}": ["general promotions", "regular promotions", "daily promotions", "common promotions", "routine promotions", "everyday promotions", "general discounts", "regular discounts", "daily discounts", "common discounts", "routine discounts", "everyday discounts", "general offers", "regular offers", "daily offers", "common offers", "routine offers", "everyday offers"],
    "${available to}": ["available to", "accessible to", "open to", "provided for", "eligible for", "available for", "provided to", "given to", "reachable by"],
    "${all customers}": ["all customers", "all shoppers", "all buyers", "all guests", "every customer", "every shopper", "every buyer", "every guest", "every consumer group"],
    "${save money}": ["save money", "get savings", "enjoy savings", "receive savings", "unlock savings", "access savings", "claim savings", "gain savings", "obtain savings", "save big"],
    # "${through}": ["through", "via", "with"],
    "${special savings events}": ["special savings events", "special sales", "special promotions", "special sale events", "seasonal savings events", "seasonal sales", "seasonal promotions", "seasonal sale events", "limited-time savings events", "limited-time sales", "limited-time promotions", "limited-time sale events", "seasonal promotion events", "featured savings events", "featured sales", "featured promotions", "featured sale events", "featured promotional events", "holiday savings events", "holiday sales", "holiday promotions", "holiday sale events"],
    "${such as}": ["such as", "like"],
    "${Memorial Day}": ["Memorial Day", "Veterans Day", "Armed Forces Day", "Independence Day", "Marine Corps Birthday", "Navy Day", "Air Force Day", "National POW/MIA Recognition Day", "Coast Guard Day", "Gold Star Mother's and Family's Day"],
    "${find}": ["find", "get", "enjoy", "grab", "unlock", "embrace", "snag"],
    "${deals}": ["deals", "sales", "discounts", "savings", "promotions", "specials", "offers"],
    "${ongoing}": ["ongoing", "regular", "specific", "dedicated", "active", "actively running", "specialized", "exclusive"],
    "${explore}": ["explore", "discover", "find", "consider", "try"],
    "${their}": ["their", "the"],
    "${provides}": ["provides", "offers", "features", "includes"],
    "${purchases}": ["purchases", "orders", "your purchases", "your orders", "your ${BRAND_NAME} purchases", "your ${BRAND_NAME} orders"],
    "${first-time customers}": ["first-time customers", "first-time shoppers", "first-time buyers", "new customers", "new shoppers", "new buyers", "new consumers"],
    "${by signing up for their email newsletter}": ["by ${signing up for} ${their} email newsletter", "through the email sign-up", "by joining ${their} mailing list", "via newsletter registration", "through subscribing to ${their} emails", "with an email subscription", "by enrolling in ${their} newsletter", "through joining ${their} email list", "by ${signing up for} email alerts", "through newsletter sign-up", "by subscribing ${their} email newsletter", "via email signup", "with a newsletter signup", "via mailing list subscription", "by registering for ${BRAND_NAME} email updates", "through newsletter enrollment", "with a mailing list signup", "by joining ${BRAND_NAME} email alerts"],
    "${signing up for}": ["enrolling in", "registering for", "subscribing to", "joining"],
    "${seasonal promotions}": ["seasonal promotions", "recurring promotions", "promotional events", "seasonal discounts", "recurring discounts", "seasonal offers", "recurring offers", "limited-time promotions", "limited-time discounts", "limited-time offers", "seasonal promos", "recurring promos", "limited-time promos", "holiday promotions", "holiday discounts", "holiday offers", "holiday promos"],
    "${special deals}": ["special deals", "exclusive deals", "unique deals", "flash deals", "special sales", "exclusive sales", "unique sales", "flash sales"],
    "${available on}": ["available on", "featured on", "provided on", "accessible on"],
    "${discount}": ["discount", "discount program"],
    "${sign up for}": ["sign up for", "register for", "enroll in", "join", "subscribe to"],
    "${newsletter}": ["mailing list", "email updates", "email alerts", "email list"],
    "${exclusive promotions}": ["special promotions", "exclusive promotions", "unique promotions", "seasonal promotions", "amazing promotions", "fantastic promotions", "unbeatable promotions", "wonderful promotions", "unbelievable promotions", "incredible promotions", "exciting promotions", "awesome promotions", "excellent promotions", "impressive promotions", "hot promotions", "super promotions"],
    "${limited-time sales}": ["limited-time sales", "limited-time deals", "flash deals", "flash sales", "limited-time discounts", "limited-time offers", "holiday discounts", "holiday offers"],
    "${redeem}": ["redeem", "enjoy", "get", "receive", "take", "grab", "unlock", "claim", "access"],
    "${check}": ["check", "visit", "head over to", "head to", "go to", "browse", "review", "explore"],
    "${Military Discount page}": ["Military Discount page", "Military Discounts page", "Military Discount section", "Military Discounts section"],
    "${verify your military status}": ["${verify} your military status", "${verify} your status as ${a} ${military member}", "${verify} your status", "confirm your eligibility", "verify your eligibility", "prove your eligibility"],
    "${verify}": ["verify", "confirm", "validate", "authenticate", "substantiate", "prove", "identify"],
    "${military member}": ["military member", "military personnel", "service member", "military staff", "military service member"],
    "${Once verified}": ["once verified", "once confirmed", "once approved", "after successful verification", "after verification", "after confirmation", "upon verification", "upon confirmation", "upon approval", "upon authentication"],
    "${qualifying items}": ["eligible items", "qualifying items", "eligible products", "qualifying products", "your purchases", "your items", "your orders", "your products", "your order total", "your cart total", "your final amount", "your billing amount"],
    # "${with}": ["through", "via", "with", "using"],
    "${receive}": ["enjoy", "get", "receive", "take", "obtain", "unlock", "claim", "access"],
    "${immediately}": ["immediately", "instantly", "straight away", "right now", "right away"],
}
