args_source_map = {
    "${deals and promotions}": ["deals and promotions", "promotions and deals", "promotions", "deals", "deals and discounts", "sales and promotions", "promos and discounts", "promos and deals", "promos and sales", "discounts and deals", "discounts and sales", "discounts and promotions", "promotions and discounts", "promotions and sales", "sales and discounts", "sales"],
    "${products}": ["products", "items", "merchandise"],
    # "${products1}": ["与${products}取值范围相同，但与${products}不能取同一值"],
    "${especially}": ["especially", "particularly", "typically", "often", "generally", "usually", "commonly"],
    "${sales}": ["sales", "deals", "sale events", "savings events", "special sales", "seasonal events", "seasonal deals", "seasonal sales", "flash sales", "flash deals", "limited-time offers", "limited-time sales", "limited-time deals", "exclusive offers", "exclusive sales", "exclusive deals", "seasonal sale events"],
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${begin}": ["begin", "start", "kick off"],
    "${leading up to}": ["leading up to", "ahead of", "before", "right before", "prior to", "just before", "leading to"],
    # "${leading up to1}": ["与${leading up to}取值范围相同，但与${leading up to}不能取同一值"],
    "${continue through}": ["continue through", "extend through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "extend throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout", "remain live through", "remain live throughout", "extend into", "continue until", "extend until", "last until", "carry on until", "span through", "remain active until", "remain available until", "stay live until", "remain live until"],
    "${deals}": ["deals", "sales"],
    "${Valentine's Day on February 14th}": ["Valentine's Day on February 14th", "Valentine's Day (February 14th)", "Valentine's Day", "February 14th", "Valentine's Day on Feb. 14th", "Valentine's Day (Feb. 14th)", "Feb. 14th", "the Romantic Day of February 14th", "the Romantic Day of Feb. 14th", "February 14th, Valentine's Day", "February 14, the day of love", "the romantic holiday (February 14)"],
    "${extend through}": ["continue through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout", "remain live through", "remain live throughout", "span through"],
    "${the end of the week}": ["the end of the week", "the weekend", "the holiday weekend", "the upcoming weekend"],
    "${stay informed about}": ["stay informed about", "keep track of", "be informed about", "get the scoop on", "keep updated on"],
    "${subscribe to}": ["subscribe to", "enroll in", "register for", "sign up for"],
    "${newsletter}": ["newsletter", "email newsletter", "mailing list", "email list", "email alerts"],
    "${follow}": ["follow", "explore", "stay tuned to", "visit"],
    "${social media}": ["social media", "social media channels"],
    "${stay updated on the latest}": ["stay updated on the newest", "keep informed of the newest", "stay current with the newest", "get the newest", "keep up with the newest", "catch the newest", "receive updates on the newest", "stay updated on the latest", "keep informed of the latest", "stay current with the latest", "get the latest", "keep up with the latest", "catch the latest", "receive updates on the latest", "stay updated on the most current", "keep informed of the most current", "get the most current", "keep up with the most current", "catch the most current", "receive updates on the most current", "keep informed of the up-to-date", "stay current with the up-to-date"],
    "${continue until}": ["continue until", "extend until", "last until", "carry on until", "remain active until", "remain available until", "stay live until", "remain live until"],
    "${around}": ["around", "about"],
    "${the 16th February}": ["February 16th", "Feb 16", "Feb. 16th"],
    "${keep updated on}": ["stay informed about", "keep track of", "be informed about", "get the scoop on", "keep updated on", "stay updated on", "keep informed of", "stay current with", "keep up with", "catch the newest", "get the newest", "receive updates on", "get the latest", "catch the latest", "get the most current", "catch the most current"],
    "${begins}": ["begins", "starts", "kicks off"],
    "${offering}": ["offering", "providing", "granting", "extending", "presenting", "giving", "delivering", "featuring", "releasing"],
    "${various}": ["various", "all kinds of", "a variety of", "all sorts of", "a range of", "different kinds of", "a wide range of", "an array of", "plenty of", "a diverse range of"],
    "${Look for}": ["Look for", "Watch for", "Keep an eye out for", "Search for", "Stay alert for", "Check out", "Hunt for", "Keep watch for", "Pay attention to", "Seek out", "Look out for"],
    "${particularly}": ["particularly", "especially", "specifically"],
    "${February 14th}": ["February 14th", "Feb 14", "Feb. 14th"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${clearance sales}": ["clearance sales", "clearance promotions", "clearance deals", "clearance discounts", "clearance event", "clearance offers"],
    "${remaining seasonal inventory}": ["leftover seasonal ${stock}", "excess seasonal ${stock}", "post-season ${stock}", "remaining seasonal ${stock}", "end-of-season ${stock}", "extra seasonal ${stock}", "seasonal overstock", "overstock from the season", "leftover ${stock} from the season", "excess ${stock} from the season", "remaining ${stock} from the season", "extra ${stock} from the season"],
    "${stock}": ["stock", "items", "goods", "products", "inventory", "merchandise"],
    "${a great}": ["an excellent", "a prime", "a favorable", "the best", "an ideal", "a great", "a fantastic", "a wonderful", "an amazing", "a superb", "a terrific", "a perfect", "a golden", "a top-notch", "a remarkable", "a favorable", "an exceptional"],
    "${opportunity}": ["opportunity", "chance", "occasion", "moment", "time"],
    "${clearance items}": ["clearance items", "promotion items", "discounted items", "sale items", "clearance products", "promotion products", "discounted products", "sale products"],
    "${expect}": ["find", "expect", "enjoy", "take advantage of", "get", "claim", "grab", "take", "unlock", "receive"],
    "${Valentine's Day sales}": ["Valentine's Day ${deals}", "Lovers' Day ${deals}", "Valentine's ${deals}", "Saint Valentine's Day ${deals}", "Saint Valentine's ${deals}"],
    "${depending on}": ["depending on", "based on", "subject to", "according to", "in accordance with"],
    "${promotions and items}": ["promotions and ${products}", "offers and ${products}", "${products} and promotions", "${products} and offers"],
    "${ranging from 20% to 60%}": ["ranging from ${20%} to ${60%}", "spanning ${20%} to ${60%}", "spanning from ${20%} to ${60%}", "from ${20%} to ${60%}", "extending from ${20%} to ${60%}", "from ${20%} up to ${60%}", "varying between ${20%} to ${60%}"],
    "${20%}": ["20%", "30%"],
    "${60%}": ["50%", "60%", "70%", "50% or more", "60% or more", "70% or more"],
    "${selected}": ["selected", "featured", "popular"],
    "${sitewide}": ["sitewide", "site-wide"],
    "${during}": ["during", "throughout", "in the course of", "over the course of", "at the time of", "over the time of", "within the period of", "during the course of"],
    "${like}": ["like", "such as", "as", "including"],
}
