args_source_map = {
    "${Black Friday sales}": ["Black Friday sales", "Black Friday deals", "Black Friday discounts", "Black Friday promotions", "Black Friday sale events", "Black Friday shopping event", "Black Friday deals events", "Black Friday mega sale", "Black Friday savings spree", "Black Friday super sale", "Black Friday price cuts", "Black Friday flash sales", "Black Friday promotional events", "Black Friday holiday deals", "Black Friday holiday sales", "Black Friday sales event", "Black Friday seasonal sales", "Black Friday exclusive sales", "Black Friday flash deals", "Black Friday seasonal deals", "Black Friday seasonal discounts", "Black Friday seasonal promotions", "Black Friday exclusive deals", "Black Friday limited-time deals", "Black Friday limited-time sales", "Black Friday limited-time discounts", "Black Friday limited-time promotions", "Black Friday savings event"],
    "${ranging from 30% to 70%}": ["ranging from ${30%} to ${70%}", "spanning ${30%} to ${70%}", "spanning from ${30%} to ${70%}", "from ${30%} to ${70%}", "extending from ${30%} to ${70%}", "from ${30%} up to ${70%}", "varying between ${30%} to ${70%}"],
    "${30%}": ["20%", "30%"],
    "${70%}": ["60%", "70%", "60% or more", "70% or more"],
    "${every year}": ["every year", "each year"],
    "${sales}": ["sales", "deals"],
    "${start}": ["start", "begin"],
    "${leading up to}": ["leading up to", "ahead of", "before", "right before", "prior to", "just before"],
    "${go on through}": ["continue through", "extend through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "extend throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout"],
    "${weekend}": ["weekend", "holiday weekend", "shopping weekend", "weekend of the holiday season"],
    "${into}": ["into", "until"],
    "${offers}": ["offers", "provides", "rolls out", "holds", "runs", "has"],
    "${deals}": ["deals", "sales", "promotions", "mega sales", "mega deals", "super sales", "super deals", "holiday deals", "holiday sales", "holiday promotions"],
    "${In recent years}": ["In recent years", "In the past few years", "Over the last few years", "In the last few years", "During the last few years", "Over the past few years", "During the past few years", "over the recent years", "during the recent years", "In the past couple of years", "Over the last couple of years", "In the last couple of years", "During the last couple of years", "Over the past couple of years", "During the past years", "In the past several years", "Over the last several years", "In the last several years", "During the last several years", "Over the past several years", "During the past several years"],
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    # "${typically1}": ["与${typically}取值范围相同，但与${typically}不能取同一值"],
    "${started}": ["started", "began", "launched", "kicked off", "rolled out"],
    "${promotions}": ["event", "sale event", "discounts", "sale events", "discounts", "shopping event", "deals events", "mega sale", "super sale", "flash sales", "flash deals", "sales event", "seasonal sales", "exclusive sales", "seasonal deals", "seasonal discounts", "seasonal promotions", "exclusive deals", "limited-time deals", "limited-time sales", "limited-time discounts", "limited-time promotions", "savings event"],
    "${on the evening}": ["on the evening", "in the evening", "at the night", "at midnight"],
    "${went on through}": ["continued through", "extended through", "ran through", "lasted through", "went on through", "carried on through", "kept going through", "continued throughout", "extended throughout", "ran throughout", "lasted throughout", "went on throughout", "carried on throughout", "kept going throughout", "remained active through", "remained active throughout", "remained available through", "remained available throughout", "stayed live through", "stayed live throughout"],
    "${extending into}": ["extending into", "continuing into", "leading into", "running into", "lasting until"],
    "${sales event}": ["sales event", "sale event", "sale events", "deals events", "mega sale", "super sale", "flash sales", "flash deals", "savings event", "promotions", "shopping event"],
    "${products}": ["products", "items", "merchandise"],
    "${discounts}": ["discounts", "savings"],
    "${at least}": ["at least", "no less than", "not less than"],
    "${many}": ["many", "a lot of", "a variety of", "plenty of", "a wide range of", "numerous", "a large number of", "a great number of", "various", "multiple", "many kinds of"],
    "${reduced}": ["reduced", "marked down", "discounted"],
    "${50%}": ["50%", "55%", "60%", "65%", "70%", "75%"],
    "${an excellent}": ["an excellent", "a prime", "a favorable", "the best", "an ideal", "a great", "a fantastic", "a wonderful", "an amazing", "a superb", "a terrific", "a perfect", "a golden", "a top-notch", "a remarkable"],
    "${opportunity}": ["opportunity", "chance", "occasion", "moment", "time"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${enjoy}": ["enjoy", "get", "receive", "take", "grab", "unlock", "claim", "access", "embrace", "take advantage of", "make use of", "seize", "benefit from", "make the most of", "score"],
    "${well in advance of}": ["well in advance of", "well ahead of", "well before", "much earlier than", "well prior to", "in advance of", "before", "ahead of", "prior to", "earlier than"],
    "${early deals}": ["early deals", "early sales", "early promotions", "early discounts", "early offers", "early special offers", "pre-sale offers", "pre-holiday deals", "pre-holiday sales", "pre-holiday promotions", "pre-holiday discounts", "pre-holiday offers", "early bird deals", "early bird sales", "early bird promotions", "early bird discounts", "early bird offers", "holiday deals", "holiday sales", "holiday promotions", "holiday discounts", "holiday offers", "special deals", "special sales", "special promotions", "special discounts", "special offers", "early promos", "pre-holiday promos", "early bird promos", "holiday promos", "special promos"],
    "${promos}": ["deals", "sales", "promotions", "discounts", "offers", "special offers", "promos"],
    "${as early as the beginning of November}": ["in early November", "at the beginning of November", "as early as the beginning of November", "right at the start of November", "from the start of November", "from the first days of November", "around the start of November", "from the very start of November", "at the start of November", "in the first week of November", "in the early days of November", "by early November", "as November begins", "by the start of November", "as November kicks off", "around the beginning of November", "right from the beginning of November", "at the very start of November", "when November begins", "when November kicks off", "early in November", "in the first days of November", "as early as the start of November"],
    "${starts}": ["starts", "begins", "launches", "kicks off", "rolls out"],
}
