args_source_map = {
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${deals and promotions}": ["deals and promotions", "promotions and deals", "promotions", "deals", "deals and discounts", "sales and promotions", "promos and discounts", "promos and deals", "promos and sales", "discounts and deals", "discounts and sales", "discounts and promotions", "promotions and discounts", "promotions and sales", "sales and discounts", "sales"],
    "${Easter season}": ["Easter season", "Easter Day", "Easter week", "Easter weekend", "holiday season", "Easter holiday season", "spring season", "spring holiday season"],
    "${Easter-themed products}": ["festive items", "festive products", "festive merchandise", "festive supplies", "Easter items", "Easter products", "Easter merchandise", "Easter supplies", "Easter-themed items", "Easter-themed products", "Easter-themed merchandise", "Easter-themed supplies", "Easter-related items", "Easter-related products", "Easter-related merchandise", "Easter-related supplies", "festive stuff", "Easter stuff", "Easter-themed stuff", "Easter-related stuff", "festive collection", "Easter collection", "Easter-themed collection", "Easter-related collection"],
    "${easter items}": ["candies", "decorations", "toys", "apparel", "home goods"],
    # "${easter items2}": ["与${easter items1}取值范围相同，但与${easter items1}不能取同一值"],
    # "${easter items3}": ["与${easter items1}取值范围相同，但与${easter items1}，${easter items2}不能取同一值"],
    # "${easter items4}": ["与${easter items1}取值范围相同，但与${easter items1}，${easter items2}，${easter items3}不能取同一值"],
    # "${easter items5}": ["与${easter items1}取值范围相同，但与${easter items1}，${easter items2}，${easter items3}，${easter items4}不能取同一值"],
    "${leading up to}": ["leading up to", "ahead of", "before", "right before", "prior to", "just before", "leading to"],
    "${special}": ["special", "amazing", "fabuolous", "fantastic", "great", "hot", "remarkable", "unbeatable", "wonderful", "unbelievable", "incredible", "exciting", "awesome", "excellent", "impressive", "top", "super"],
    "${deals}": ["deals", "promotions", "discounts", "sales"],
    "${baskets, eggs}": ["baskets, eggs", "baskets, chocolate eggs", "baskets, sweets", "baskets, chocolates", "baskets, chocolate sweets", "eggs, baskets", "chocolate eggs, baskets", "sweets, baskets", "chocolates, baskets", "chocolate sweets, baskets"],
    "${festive essentials}": ["festive essentials"],
    "${starts}": ["begin", "kick off", "start", "launch"],
    "${continues through}": ["continues through", "extends through", "runs through", "lasts through", "goes on through", "carries on through", "keeps going through", "continues throughout", "extends throughout", "runs throughout", "lasts throughout", "goes on throughout", "carries on throughout", "keeps going throughout", "remains active through", "remains active throughout", "remains available through", "remains available throughout", "stays live through", "stays live throughout", "remains live through", "remains live throughout"],
    "${on Sun, Mar 31}": ["on Sun, April 20", "on Sunday, April 20", "on Sunday", "on April 20", "on Sun, Apr 20", "on Sunday, Apr 20", "on Apr 20, 2025", "on Sun, Apr 20, 2025"],
    "${holiday}": ["holiday", "Easter season", "Easter Day", "Easter week", "Easter Sunday", "Easter holiday season"],
    "${approaches}": ["approaches", "is coming", "nears", "draws closer", "comes around", "arrives", "is around the corner", "draws near"],
    "${especially}": ["especially", "particularly", "often", "usually"],
    "${last-minute}": ["last-minute", "smart", "savvy", "clever"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${savings}": ["savings", "discounts", "bargains"],
    "${candies}": ["candies", "eggs", "chocolates", "sweets"],
    "${Easter essentials}": ["Easter essentials", "${Easter-themed products}"],
    "${several weeks}": ["several weeks", "a few weeks", "a couple of weeks"],
    "${before}": ["before", "right before", "just before"],
    "${the Easter holiday}": ["the Easter holiday", "the Easter Day", "Easter Sunday", "Easter", "the Easter holiday itself"],
    "${usually}": ["usually", "generally", "commonly", "often"],
    "${falling}": ["falling", "arriving"],
    "${late February to early March}": ["late February to early March", "early March", "late February", "late February to mid March", "mid-February to early March", "late February through early March", "mid-to-late February", "February's end to March's start"],
    "${ranging from 20% to 60%}": ["ranging from ${20%} to ${60%}", "spanning ${20%} to ${60%}", "spanning from ${20%} to ${60%}", "from ${20%} to ${60%}", "extending from ${20%} to ${60%}", "from ${20%} up to ${60%}", "varying between ${20%} to ${60%}"],
    "${20%}": ["20%", "30%"],
    "${60%}": ["50%", "60%", "70%", "50% or more", "60% or more", "70% or more"],
    "${holiday events}": ["holiday events", "holiday promotions", "holiday sales", "holiday sale events", "season events", "season promotions", "season sales", "season sale events", "festive events", "festive promotions", "festive sales", "festive sale events", "savings events", "sale events", "saving events", "shopping events"],
    "${such as}": ["like", "such as", "including"],
    "${offers}": ["offers", "provides"],
    "${buy-one-get-one deals}": ["buy-one-get-one deals", "buy one get one deals", "2 for 1 deals", "BOGO deals", "buy-one-get-one promotions", "buy one get one promotions", "2 for 1 promotions", "BOGO promotions", "buy-one-get-one specials", "buy one get one specials", "2 for 1 specials", "BOGO specials"],
    "${spring-themed}": ["spring-themed", "spring-season"],
    "${items}": ["items", "products"],
    "${look out for}": ["Look out for", "Look for", "Pay attention to", "Check for", "Stay tuned for", "Look around for", "Keep an eye on", "Check out", "Check"],
    "${flyers, websites, advertisements}": ["${flyers}, websites and advertisements", "${flyers}, advertisements and websites", "websites, ${flyers} and advertisements", "websites, advertisements and ${flyers}", "advertisements, ${flyers} and websites", "advertisements, websites and ${flyers}"],
    "${flyers}": ["flyers", "posters", "leaflets", "banners"],
    "${stay informed about}": ["stay informed about", "keep track of", "be informed about", "get the scoop on", "keep updated on", "stay updated on", "keep informed of", "stay current with", "follow"],
    "${significant}": ["whopping", "impressive", "remarkable", "generous", "significant", "fantastic", "striking", "great", "attractive", "appealing", "amazing", "fabuolous", "hot", "unbeatable", "wonderful", "unbelievable", "incredible", "exciting", "awesome", "excellent", "top", "super", "exclusive"],
    "${extending into}": ["extending into", "extending until"],
    "${begins}": ["begins", "kicks off", "starts", "launches"],
}
