args_source_map = {
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${deals and promotions}": ["deals and promotions", "promotions and deals", "promotions", "deals", "deals and discounts", "sales and promotions", "promos and discounts", "promos and deals", "promos and sales", "discounts and deals", "discounts and sales", "discounts and promotions", "promotions and discounts", "promotions and sales", "sales and discounts", "sales"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${find gifts for their moms}": ["choose gifts for their ${moms}", "discover gifts for their ${moms}", "pick out gifts for their ${moms}", "track down gifts for their ${moms}", "select gifts for their ${moms}", "get gifts for their ${moms}", "pick up gifts for their ${moms}", "grab gifts for their ${moms}", "pick gifts for their ${moms}", "score gifts for their ${moms}", "hunt down gifts for their ${moms}", "buy gifts for their ${moms}", "find gifts for their ${moms}", "take gifts for their ${moms}"],
    "${moms}": ["moms", "mothers"],
    "${at discounted prices}": ["at discounted prices", "at lower prices", "at special prices", "at reduced prices", "with savings", "for less", "at great prices", "at unbeatable prices", "at promotional prices", "at wallet-friendly prices", "without breaking the bank", "at bargain prices", "at budget-friendly prices", "at marked-down prices", "at wallet-friendly prices", "at a steal", "at deep savings", "for a lower price", "at unbeatable savings", "at can't-miss prices", "at fabulous savings", "at incredible savings"],
    "${keep an eye on}": ["Look out for", "Look for", "Pay attention to", "Check for", "Stay tuned for", "Look around for", "Keep an eye on", "Check out", "Check"],
    "${subscribe to}": ["subscribe to", "enrol in", "register for", "sign up for"],
    "${newsletter}": ["newsletter", "email newsletter", "mailing list", "email list", "email alerts"],
    "${stay updated on the latest}": ["stay updated on the newest", "keep informed of the newest", "stay current with the newest", "get the newest", "keep up with the newest", "catch the newest", "receive updates on the newest", "stay updated on the latest", "keep informed of the latest", "stay current with the latest", "get the latest", "keep up with the latest", "catch the latest", "receive updates on the latest", "stay updated on the most current", "keep informed of the most current", "get the most current", "keep up with the most current", "catch the most current", "receive updates on the most current", "keep informed of the up-to-date", "stay current with the up-to-date"],
    "${promotions}": ["promotions", "discounts", "sales", "events", "sale events", "shopping events", "saving events"],
    "${a few}": ["a few", "several", "a couple of"],
    "${leading up to}": ["leading up to", "ahead of", "before", "right before", "prior to", "just before", "leading to"],
    "${falls on}": ["falls on", "arrives on", "is celebrated on", "lands on", "comes on", "occurs on", "happens on", "is observed on"],
    "${May 11th}": ["May 11th", "May 11, 2025", "Sunday, May 11", "May 11"],
    "${start}": ["start", "begin", "kick off", "roll out"],
    "${several days}": ["several days", "a couple of days", "a few days", "a short period"],
    "${before}": ["before", "right before", "just before"],
    "${actual}": ["real", "actual"],
    "${continue through}": ["continue through", "extend through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "extend throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout", "remain live through", "remain live throughout", "extend into", "continue until", "extend until", "last until", "carry on until", "span through", "remain active until", "remain available until", "stay live until", "remain live until"],
    "${shortly after}": ["a short time later", "shortly after", "soon after", "a short time after"],
    "${a few weeks}": ["several weeks", "a couple of weeks", "a few weeks", "a short period"],
    "${each year}": ["annually", "every year", "year after year", "each year", "once a year"],
    "${start offering}": ["start offering", "start providing", "kick off", "roll out", "begin offering", "begin providing", "launch", "release"],
    "${late April or early May}": ["late April or early May", "early May", "late April", "mid-to-late April"],
    "${deals}": ["sales", "deals", "promotions", "discounts", "special sales", "seasonal deals", "seasonal sales", "flash sales", "flash deals", "limited-time deals", "limited-time sales", "exclusive sales", "exclusive deals"],
    "${sales}": ["sales", "deals", "sale events", "savings events", "clearance", "holiday sales", "seasonal events", "seasonal deals", "seasonal sales", "event sales", "flash sales", "flash deals", "seasonal sale events"],
    "${find}": ["find", "get", "enjoy", "receive", "claim", "access", "grab", "snag", "catch", "discover", "claim", "unlock", "secure", "seize"],
    "${ranging from 10% to 50%}": ["ranging from ${10%} to ${50%}", "spanning ${10%} to ${50%}", "spanning from ${10%} to ${50%}", "from ${10%} to ${50%}", "extending from ${10%} to ${50%}", "from ${10%} up to ${50%}", "varying between ${10%} to ${50%}"],
    "${10%}": ["10%", "20%", "30%"],
    "${50%}": ["50%", "60%", "70%", "50% or more", "60% or more", "70% or more"],
    "${various}": ["various", "all kinds of", "a variety of", "all sorts of", "a range of", "different kinds of", "a wide range of", "an array of", "plenty of", "a diverse range of"],
    "${products}": ["products", "items", "merchandise", "supplies"],
    "${Additionally}": ["In addition", "Additionally", "Moreover"],
    "${often}": ["typically", "often", "usually"],
    "${such as}": ["such as", "like", "including"],
    "${buy-one-get-one (BOGO) offers}": ["buy-one-get-one deals", "buy one get one deals", "2 for 1 deals", "BOGO deals", "buy-one-get-one offers", "buy one get one offers", "2 for 1 offers", "BOGO offers", "buy-one-get-one specials", "buy one get one specials", "buy-one-get-one (BOGO) offers"],
    "${gift card incentives}": ["gift card incentives", "free gift cards", "gift cards", "eGift cards"],
    "${purchases}": ["purchases", "orders"],
    "${last for}": ["continue for", "go on for", "keep going for", "last for", "run for"],
    "${qualifying}": ["qualifying", "eligible"],
}
