args_source_map = {
    "${offers}": ["offers", "provides", "gives", "rolls out"],
    "${the best}": ["the best", "unbeatable", "exceptional", "the biggest", "the greatest", "significant", "amazing", "incredible", "excellent", "fantastic", "wonderful", "superb", "terrific", "perfect", "remarkable", "irresistible", "fabuolous", "unbelievable", "exciting", "awesome", "impressive", "super", "superior"],
    "${on both Black Friday and Cyber Monday}": ["across Black Friday and Cyber Monday", "across both Black Friday and Cyber Monday", "during Black Friday and Cyber Monday", "during Black Friday as well as Cyber Monday", "during both Black Friday and Cyber Monday", "during the Black Friday and Cyber Monday ${events}", "during the Black Friday and Cyber Monday week", "for Black Friday and Cyber Monday", "for Black Friday and Cyber Monday ${shoppers}", "for both Black Friday and Cyber Monday", "for both Black Friday and Cyber Monday ${shoppers}", "in the Black Friday and Cyber Monday ${events}", "on Black Friday and Cyber Monday", "on Black Friday and Cyber Monday deals", "on both Black Friday and Cyber Monday", "through Black Friday and Cyber Monday ${events}", "through both Black Friday and Cyber Monday ${events}", "throughout Black Friday and Cyber Monday ${events}"],
    "${events}": ["events", "sales", "promotions", "sales events", "sale events", "savings events", "saving events", "shopping events"],
    "${shoppers}": ["shoppers", "customers", "buyers", "consumers"],
    "${in-store and online sales}": ["in-store and online sales", "in-store and online deals", "online and in-store sales", "online and in-store deals", "in-store and online promos", "online and in-store promos", "retail and online sales", "online and retail sales", "retail and online deals", "online and retail deals", "retail and online promos", "online and retail promos"],
    "${primarily}": ["primarily", "mainly", "mostly", "generally", "typically", "especially", "essentially", "above all", "basically", "in essence", "basically", "substantially"],
    "${an online shopping}": ["an online shopping", "an online sale", "a website shopping", "a website sale", "an internet shopping", "an internet sale", "an e-commerce shopping", "an e-commerce sale"],
    "${products }": ["clothing", "electronics", "toys", "home appliances", "furniture", "jewelry", "sporting goods", "tech gadgets", "beauty products", "online services", "gaming"],
    # "${products 2}": ["与${products 1}取值范围相同，但与${products 1}不能取同一值"],
    # "${products 3}": ["与${products 1}取值范围相同，但与${products 1}，${products 2}不能取同一值"],
    "${both Black Friday and Cyber Monday}": ["both Black Friday and Cyber Monday", "both Black Friday and Cyber Monday ${events}"],
    # "${the best 1}": ["与${the best}取值范围相同，但与${the best}不能取同一值"],
    # "${the best 2}": ["与${the best}取值范围相同，但与${the best}，${the best 1}不能取同一值"],
    "${occasions}": ["occasions", "events", "periods"],
    "${typically}": ["typically", "often", "generally", "usually", "commonly"],
    "${start}": ["start", "begin"],
    "${the Friday following Thanksgiving}": ["the Friday following Thanksgiving", "the Friday after Thanksgiving", "the Friday after Thanksgiving Day", "the Friday following Thanksgiving Day", "the Friday that follows Thanksgiving", "the day following Thanksgiving", "the day after Thanksgiving", "the day after Thanksgiving Day", "the day following Thanksgiving Day", "the day that follows Thanksgiving", "the Friday of Thanksgiving weekend"],
    "${go on through}": ["continue through", "extend through", "run through", "last through", "go on through", "carry on through", "keep going through", "continue throughout", "extend throughout", "run throughout", "last throughout", "go on throughout", "carry on throughout", "keep going throughout", "remain active through", "remain active throughout", "remain available through", "remain available throughout", "stay live through", "stay live throughout"],
    # "${typically1}": ["与${typically}取值范围相同，但与${typically}不能取同一值"],
    "${promotions}": ["promotions", "deals", "sales", "event", "sale event", "shopping event", "saving event"],
    # "${go on through1}": ["与${go on through}取值范围相同，但与${go on through}不能取同一值"],
    "${after}": ["after", "following", "that follows"],
    "${starts}": ["starts", "begins"],
    "${midnight}": ["midnight", "12:00 AM"],
    "${runs}": ["runs", "lasts", "continues", "goes on"],
    "${for the remainder of the day}": ["for the remainder of the day", "for the rest of the day", "for the rest of that day", "for the remainder of that day", "for the entire day", "until the day ends", "until the day's end", "for the remaining hours of the day", "for the remaining hours of that day"],
    "${kicks off}": ["kicks off", "offers", "provides", "rolls out"],
    "${sale}": ["sale", "deal"],
    "${new}": ["new", "fresh", "brand-new"],
    "${deals}": ["deals", "promotions", "discounts", "offers", "promos"],
    "${released}": ["released", "launched", "unveiled", "revealed"],
    "${throughout the day}": ["throughout the day", "all day long", "during the day", "during the entire day", "through the day", "for the whole day", "all day", "across the day"],
    "${exactly}": ["exactly", "precisely", "a full"],
    "${hang around}": ["hang around", "are available", "are valid", "stay available", "stay valid", "remain available", "remain valid", "are active", "stay active", "remain active", "last"],
    "${for a whole week}": ["for a whole week", "for an entire week", "all week long", "for a full week", "throughout the week", "for a week", "all week", "for the whole week", "for the full week", "through the whole week"],
    "${50%}": ["50%", "55%", "60%", "65%", "70%", "75%"],
    "${while}": ["while", "but", "however,", "whereas", "in contrast,", "in comparison,", "on the other hand,"],
    "${involves}": ["involves", "features"],
    "${before the deals expire}": ["before the deals expire", "before the sales expire", "before the promotions expire", "before the promos expire", "before the deals end", "before the sales end", "before the promotions end", "before the promos end", "before the offers expire", "before the offers end", "before it expires"],
    "${traditionally}": ["traditionally", "usually", "often", "typically", "generally", "commonly", "historically", "customarily", "by tradition", "conventionally"],
}
